[node]
# working_dir = "/dir/to/save/chainstate" # defaults to: /tmp/stacks-node-[0-9]*
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
prometheus_bind = "0.0.0.0:9153"

# Both miner and mock_mining must be true
miner = true
mock_mining = true

[miner]
# Required: Generate with: openssl rand -hex 32
mining_key = "0000000000000000000000000000000000000000000000000000000000000001"

[burnchain]
mode = "mainnet"
peer_host = "127.0.0.1"
